site_name: ZJP's Note
repo_url: https://github.com/mo-xiaoxiu/myblog #（请修改为你自己的仓库地址）
edit_uri: "" #edit/main/docs/

# 导航栏
nav:
  - 主页: index.md
    #- 数据结构与算法:
    #- leetcode:
    #  - 二叉树:
    #    - 二叉树的先序、中序和后序遍历.md
    #    - 重建二叉树.md
    #    - binaryTree_2.md
    #  - 字符串:
    #    - 反转字符串.md
    #    - KMP.md
    #  - 数组和哈希:
    #    - 数组知识点一之二分查找.md
    #    - 数组知识点之滑动窗口.md
    #    - 数组知识点之数组元素归位.md
    #    - 数组知识点之双指针法.md
    #    - 二维数组查找.md
    #    - array_and_hashMap.md
    #  - 回溯、递归和深度优先遍历:
    #    - DFS.md
    #    - backTracking.md
    #    - recursion_and_iteration.md
    #  - 栈和队列:
    #    - STACK_QUEUE.md
    #  - 动态规划:
    #    - bag.md 
    #  - 其他:
    #    - disjoint_set.md
    #    - moore_vote.md
    #    - math.md
    #    - TrieTree.md     
    #    - 螺旋矩阵.md
    #- 数据结构与算法实现:
    #  - 链表操作:
    #    - implementation.md
    #    - List2.md
    #    - addNode_in_list_by_diff.md
    #    - list_deleteNode_by_diff.md
    #    - list_Merge_k_list.md
    #    - list_other_op.md
    #  - 排序:
    #    - radix_sort.md
    #    - bucket_sort.md 
    #    - counting_sort.md
    #  - 队列:
    #    - queue.md   
  - C/C++:
    - 跳转表.md
    - C++前置声明.md
    - C语言实现私有成员.md
    - C++检测内存泄漏工具.md
    - C实现C++虚函数.md
    - C++返回对象.md
    - const重载.md
    - C项目的构建.md
    - 内存管理.md
    - 实现一个简单的空间配置器.md
    - 编译期计算.md
    - 内存对齐.md
    - design_pattern.md
    - RRTI.md
    - pointer_1.md
    - smart_ptr.md
    - time.md
    - lambda.md
    - 设计模式详解:
      - C++单例模式.md
    - web服务器实现:
      - 线程同步:
        - 线程同步机制封装类.md
      - 线程池:
        - 线程池.md
      - http连接处理:
        - 知识储备:
          - epoll.md
          - one_loop_one_thread.md
          - 有限状态机.md
    - 网络编程:
      - SIGPIPE.md
      - Reactor模式.md
      - 服务器程序架构(ep).md
      - 解决粘包半包.md
      - select_poll_epoll.md
      - socket_calculate.md
      - 网络编程知识点随记.md
  - 网络:
    - Cookie_Session_Token.md
    - RSA_TLS三次握手.md
    - RSA_ECDHE密码套件.md
    - HTTPS_ECDHE握手解析.md
    - TIME_WAIT问题.md
  - Linux以及基础:
    - splice().md
    - CAN.md
    - 函数调用.md
    - Linux运行的硬件基础.md
    - 理解了实现再谈网络性能笔记.md
  - 多线程编程:
    - thread.md
    - Linux多线程服务器编程笔记.md  
  - 数据库:
    - 数据库笔记.md
  - 其他:
    - 博客中的图片显示不出怎么办？.md
    - CMake.md
    - Redis多路复用.md
    - GIt.md
    - shell教程.md
    - UML类图.md
    - study_makefile.md
    - MYSQL_C_API.md
  # 测试模块
  # - TEST:
    # - testAddArticle.md


theme:
    name: material
    palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    language: zh
    # change logo
    logo: logo/logo.png
    # change favicon
    favicon: logo/logo.png
    # 设置导航
    features:
    - navigation.tabs # 导航栏
    - navigation.tracking # 锚点跟踪
    - navigation.sections # 侧边栏目录显示
    - navigation.expand # 侧边栏目录文件夹可折叠

    # github图标
    # icon:
      # repo: fontawesome/brands/git-square


# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  # - pymdownx.arithmatex
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  # - pymdownx.tasklist:
  #     custom_checkbox: true
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - admonition

  # code highlight
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


plugins:
  - search
  - roamlinks 

extra:
  generator: false # 不显示 MkDocs 的版权

copyright: Copyright &copy; 2020 - 2022 ZJP 
